#!/usr/bin/env bash

set -e

if [[ "${EUID}" -eq 0 ]]; then
    echo "Do not run install.sh with sudo."
    echo "Run it as your normal user from the repository root:"
    echo "./install.sh"
    exit 1
fi

REPO_DIR="$(pwd)"
RUN_USER="$(id -un)"
VENV_PYTHON="${REPO_DIR}/.venv/bin/python"
SERVICE_PATH="/etc/systemd/system/shadowbox.service"
DEFAULT_ENV_PATH="/etc/default/shadowbox"
DISPLAY_KIND="${SHADOWBOX_DISPLAY:-st7789_raw}"

echo "Shadowbox installer"
echo "==================="
echo "Display backend: ${DISPLAY_KIND}"

echo "Updating system..."
sudo apt update

echo "Installing system dependencies..."
sudo apt install -y \
    python3-venv \
    python3-pip \
    pigpio \
    libopenjp2-7 \
    python3-spidev \
    python3-rpi.gpio

case "${DISPLAY_KIND}" in
    ssd1306|ssd1309)
        echo "Installing OLED/I2C dependencies..."
        sudo apt install -y \
            python3-smbus \
            i2c-tools

        echo "Enabling I2C..."
        sudo raspi-config nonint do_i2c 0
        ;;
    st7789|st7789_raw|waveshare_2inch)
        echo "Skipping I2C setup for TFT display backend."
        ;;
    *)
        echo "Unknown SHADOWBOX_DISPLAY='${DISPLAY_KIND}'."
        echo "Skipping display-specific I2C setup."
        ;;
esac

echo "Enabling SPI..."
sudo raspi-config nonint do_spi 0

echo "Starting pigpio daemon..."
sudo systemctl enable pigpiod
sudo systemctl start pigpiod

echo "Creating Python virtual environment..."
python3 -m venv .venv

echo "Activating venv..."
source .venv/bin/activate

echo "Installing Python dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

echo "Persisting Shadowbox environment..."
TMP_ENV="$(mktemp)"
if sudo test -f "${DEFAULT_ENV_PATH}"; then
    sudo cat "${DEFAULT_ENV_PATH}" > "${TMP_ENV}"
else
    cat > "${TMP_ENV}" <<EOF
# Shadowbox runtime configuration
# Generated by install.sh
EOF
fi

while IFS= read -r env_line; do
    key="${env_line%%=*}"
    if grep -q "^${key}=" "${TMP_ENV}"; then
        sed -i.bak "s|^${key}=.*|${env_line}|" "${TMP_ENV}"
        rm -f "${TMP_ENV}.bak"
    else
        printf '%s\n' "${env_line}" >> "${TMP_ENV}"
    fi
done < <(env | LC_ALL=C sort | grep '^SHADOWBOX_')

if ! grep -q '^SHADOWBOX_DISPLAY=' "${TMP_ENV}"; then
    printf 'SHADOWBOX_DISPLAY=%s\n' "${DISPLAY_KIND}" >> "${TMP_ENV}"
fi

sudo install -m 0644 "${TMP_ENV}" "${DEFAULT_ENV_PATH}"
rm -f "${TMP_ENV}"

echo "Installing systemd service..."
sudo tee "${SERVICE_PATH}" >/dev/null <<EOF
[Unit]
Description=Shadowbox RNBO Hardware UI
Wants=pigpiod.service
After=network.target pigpiod.service

[Service]
User=${RUN_USER}
WorkingDirectory=${REPO_DIR}
ExecStart=${VENV_PYTHON} -m shadowbox.shadowbox
Restart=always
RestartSec=3
Environment=PYTHONUNBUFFERED=1
EnvironmentFile=-/etc/default/shadowbox

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable shadowbox

echo "Starting Shadowbox..."
sudo systemctl restart shadowbox

echo ""
echo "Install complete."
echo ""
echo "Reboot recommended:"
echo "sudo reboot"
echo ""
echo "Runtime configuration saved to ${DEFAULT_ENV_PATH}"
